version: "3.9"
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.defaults
    ports:
      - "${PROXY_PORT:-5000}:${PROXY_PORT:-5000}"
    command: [ "/usr/local/bin/3proxy", "${PROXY_CONFIG:-/tmp/3proxy.conf}" ]
