name: Build Docker image

on:
  workflow_dispatch:
  push:
    paths:
      # build again on modified Dockerfile
      - Dockerfile

env:
  PLATFORMS: "linux/amd64, linux/arm64"

jobs:
  docker-threeproxy:
    name: Build 3proxy image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build force-adverse/3proxy
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{env.PLATFORMS}}
          tags: ghcr.io/force-adverse/3proxy-docker:latest
          file: ./Dockerfile